In [2]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence

In [3]:
# 전처리할 텍스트를 정합니다
text = "해보지 않으면 해낼 수 없다"

#해당 텍스트를 토큰화합니다.
result = text_to_word_sequence(text)
print("\n원문 : \n", text)
print("\n토큰화 : \n",result)


원문 : 
 해보지 않으면 해낼 수 없다

토큰화 : 
 ['해보지', '않으면', '해낼', '수', '없다']


In [4]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [5]:
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
'텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
'토큰화한 결과는 딥러닝에서 사용할 수 있습니다.']

In [6]:
token = Tokenizer() #토큰화 함수 지정
token.fit_on_texts(docs) #토큰화 함수에 문장 적용

print('\n단어 카운트 : \n',token.word_counts) # 단어의 빈도수를 계산한 결과값 출력


단어 카운트 : 
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [7]:
print("\n문장 카운트 : ",token.document_count)


문장 카운트 :  3


In [8]:
print("\n각 단어가 몇 개의 문장에 포함되어 잇는가 : \n",token.word_docs)


각 단어가 몇 개의 문장에 포함되어 잇는가 : 
 defaultdict(<class 'int'>, {'나누어': 1, '텍스트의': 2, '토큰화합니다': 1, '각': 1, '단어를': 1, '먼저': 1, '토큰화해야': 1, '단어로': 1, '딥러닝에서': 2, '인식됩니다': 1, '토큰화한': 1, '있습니다': 1, '수': 1, '사용할': 1, '결과는': 1})


In [9]:
print("\n각 단어에 매겨진 인덱스 값 : \n",token.word_index)


각 단어에 매겨진 인덱스 값 : 
 {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화합니다': 7, '단어로': 8, '토큰화해야': 9, '인식됩니다': 10, '토큰화한': 11, '결과는': 12, '사용할': 13, '수': 14, '있습니다': 15}


In [10]:
text = "오랫동안 꿈꾸는 이는 그 꿈을  닮아간다"

token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [11]:
x = token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [12]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense,Flatten,Embedding
from tensorflow.keras.utils import to_categorical

from numpy import array

In [13]:
# 인덱스 수에 하나를 추가해서 원-핫 인코딩 배열 만들기
word_size = len(token.word_index) + 1
x = to_categorical(x,num_classes=word_size)

print(x)


[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


In [19]:
from tensorflow.python.keras.layers import Embedding
from tensorflow.python.keras.models import Sequential


In [24]:
model = Sequential()
model.add(Embedding(16,4))

In [25]:
# 텍스트 리뷰 자료를 지정합니다.
docs = ["너무 재밌네요.","최고에요","침 잘 만든 영화예요","추천하고 싶은 영화입니다","한 번 더 보고싶네요","글쎄요","별로에요","생각보다 지루하네요","연기가 어색해요","재미없어요"]

#긍정 리뷰는 1, 부정리뷰는 0으로 클래스를 지정합니다.
classes = array([1,1,1,1,1,0,0,0,0,0])

#토큰화 
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)#토큰화된 결과를 출력해 확인합니다.

{'너무': 1, '재밌네요': 2, '최고에요': 3, '침': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한': 11, '번': 12, '더': 13, '보고싶네요': 14, '글쎄요': 15, '별로에요': 16, '생각보다': 17, '지루하네요': 18, '연기가': 19, '어색해요': 20, '재미없어요': 21}


In [26]:
x = token.texts_to_sequences(docs)
print("\n리뷰 텍스트, 토큰화 결과\n",x)

#패딩 , 서로 다른길이의 데이터를 4로 맞추어 줍니다.
padded_x = pad_sequences(x,4)
print('\n리뷰 텍스트 ,토큰화 결과값 : ',padded_x)



리뷰 텍스트, 토큰화 결과
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13, 14], [15], [16], [17, 18], [19, 20], [21]]

리뷰 텍스트 ,토큰화 결과값 :  [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [11 12 13 14]
 [ 0  0  0 15]
 [ 0  0  0 16]
 [ 0  0 17 18]
 [ 0  0 19 20]
 [ 0  0  0 21]]


In [27]:
#임베딩에 입력될 단어의 수를 지정합니다
word_size = len(token.word_index) +1 

In [28]:
#단어 임베딩을 포함해 딥러닝 모델을 만들고 결과를 출력합니다. 
model = Sequential()
model.add(Embedding(word_size, 8 , input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.summary()

model.compile(optimizer='adam', loss= 'binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x,classes , epochs=20)
print("\nAcuuracy : %.4f"%(model.evaluate(padded_x,classes)[1]))



Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 4, 8)              176       
_________________________________________________________________
flatten_2 (Flatten)          (None, 32)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 33        
Total params: 209
Trainable params: 209
Non-trainable params: 0
_________________________________________________________________
Epoch 1/20
1/1 [==============================] - 0s 277ms/step - loss: 0.6917 - accuracy: 0.5000
Epoch 2/20
1/1 [==============================] - 0s 1000us/step - loss: 0.6892 - accuracy: 0.6000
Epoch 3/20
1/1 [==============================] - 0s 1000us/step - loss: 0.6866 - accuracy: 0.6000
Epoch 4/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6841 - accuracy: 0